feat(runtime): enhance the access protection security model
MaskingTechnology/jitar pull request #452
Opened 2024-01-26 14:03 UTC by BasMasking

Fixes #448

Changes proposed in this pull request:
- added option to created trusted clients
- added protected access for procedures
- updated documentation
- updated example to reflect the change

@MaskingTechnology/jitar

2024-01-26 20:25 UTC, petermasking requested changes

2024-01-26 20:25 UTC, petermasking commented on examples/concepts/access-protection/segments/game.segment.json
Is it more clear to rename this segment to `protected.segment.json`?

2024-01-26 20:25 UTC, petermasking commented on examples/concepts/access-protection/segments/web.segment.json
Is it more clear to rename this segment to `public.segment.json`

2024-01-26 20:25 UTC, petermasking commented on packages/runtime/src/models/Procedure.ts
> +    {
Should we mention this in the docs?

2024-01-26 20:25 UTC, petermasking commented on packages/runtime/src/services/LocalNode.ts
> +        const secret = request.headers.get('x-access-key');
```suggestion
        const secret = request.getHeader('x-access-key');
```

2024-01-26 20:25 UTC, petermasking commented on packages/runtime/test/services/LocalGateway.spec.ts
I'm missing a test for a failing registration of a node, and protected related test in the local node spec.

2024-01-26 20:33 UTC, BasMasking commented on documentation/docs/deploy/segmentation.md
> +Any client that wants to access a protected function must provide a valid access key. The access key needs to be added to the http header `x-access-key`. Any node that has a valid access key is consi
Good suggestion, I changed the header key.

2024-01-26 20:44 UTC, BasMasking commented on documentation/docs/fundamentals/runtime-services.md
> +* secret - shared secret for creating trusted clients (optional).
It's a string to access the protected procedures, so I go for the `protectedAccessKey` for now. Any suggestions are welcome.

2024-01-26 23:06 UTC, petermasking requested changes
Besides the other review comments I'm still missing the tests for the local node. At least for running a protected procedure with a key, with an invalid key and a valid key.

2024-01-27 19:22 UTC, petermasking requested changes

2024-01-27 19:22 UTC, petermasking commented on examples/concepts/access-protection/requests.http
> +X-Jitar-Protected-Access-Key: VERY_SECRET_KEY
```suggestion
X-Jitar-Trust-Key: VERY_SECRET_KEY
```

2024-01-27 19:22 UTC, petermasking commented on documentation/docs/deploy/segmentation.md
> +Any client that wants to access a protected function must provide a valid key. It needs to be added to the http header `X-Jitar-Protected-Access-Key`. Any node that has a valid key is automatically c
The key has been changed in the code, but not in the docs yet.

2024-01-27 19:32 UTC, petermasking approved these changes

2024-01-27 19:32 UTC, merged