feat: add index resolution for modules, resources and segments
MaskingTechnology/jitar pull request #590
Opened 2024-12-27 23:29 UTC by basmasking

Fixes #572

Changes proposed in this pull request:
- resolve `index.js` in case of directory reference

There are no tests yet. This feature can be tested using Comify, branch [#361](https://github.com/MaskingTechnology/comify/issues/361)

@MaskingTechnology/jitar

2024-12-30 10:42 UTC, petermasking submitted a review, later dismissed

2025-01-03 12:12 UTC, petermasking requested changes

2025-01-03 12:12 UTC, petermasking commented on packages/build/src/source/module/LocationRewriter.ts
> +
```suggestion

// The location rewriter ensures the '.js' for all application imports and re-exports
// and appends the 'index.js' reference for all directory imports.

```

2025-01-03 12:12 UTC, petermasking commented on packages/sourcing/src/LocalFileSystem.ts
> +    // LocationRewriter. This class uses a replacer function
The `LocationRewriter` comes from a different package and has nothing to do with this class. Making a function synchronous for this reason violates the class independence. Can we still justify keeping this function synchronous?

2025-01-03 12:36 UTC, basmasking commented on documentation/docs/develop/application-structure.md
> +   ├─ ...
Created the following [Issue](https://github.com/MaskingTechnology/jitar/issues/595) so we can keep track of these items.

2025-01-03 13:13 UTC, merged